language:
  - python
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run manage.py test
after_success:
  - coveralls
  - fab deploy
env:
  global:
    secure: "GcNMn0OeXMIf/jxskh7BsVXqGj0MKooj+zaUKzvLnyd6JZKWehj600D05lnYLLZiNoTygcImPJLonjmbKwKkkfjIFuLLrl2fkvwlneru0rM9h80g7dMW18HPbD0DydlEtrmrY8cBvmJe+XtRdG1O2pu1ufwaP/kVijtqrBKyfyM="
