language:
  - python
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run manage.py test
after_success:
  - coveralls
  - fab deploy
env:
  global:
    secure: "LTJnFo3rmnh2QAY4gyPnTbrwH6wwyohQx5xj2bLD078a2A6G87d9P1dtGkCR6+bZCgkVTJE2Kx+xg8cWolY5zqffGYShpZQrfawkL2BId7x+JbHzVSP20u7LNtqysctpxRL7LbDTiAO+MdVzgw7HU+OkXmRtEsDeeANgCMbeRWA="
notifications:
  email:
    recipients:
      - luanfonceca@gmail.com