sudo: false
language:
  - python
install:
  - pip install -r requirements.txt
script:
  - coverage run manage.py test
after_success:
  - coveralls
  - if ([ "$TRAVIS_BRANCH" == "master" ]); then fab deploy; fi
env:
  global:
    - secure: fp6OgeBAhwSJ/xXwh2y28ODMQMwi9xuOFaon3CKNZ7Jfh9Suwm8sSrVbA3gt7OcrhZOINU8vlMSiVgXS5cIYlDtty8GOykFMA2ERasZSTSeo9JHmtL4skR/avZNqlczOd5dycteRgiDCNWiK7BGqnKHDACuksEdnzu63WDZF1h0=
